### ISSUE TITLE
Doesn't work with multiple files

### ISSUE THREAD

**Issue by aiwha-dev** [vitaliy-bobrov/angular-hot-loader#28]
It doesn't seem to work properly with multiple files for module/controller

for example we've got

page.module.js
```
'use strict';
import angular from 'angular';
(function( angular ) {
    angular.module('page', [
        'injections'
    ]);
})();

```

page.routes.js
```
'use strict';
import angular from 'angular';
(function( angular ) {

	angular.module('page' )
		.config( PageRouteConfig );

	PageRouteConfig.$inject = [
		'$stateProvider'
	];

	function PageRouteConfig(
		$stateProvider
	) {

		$stateProvider.state( { 
			name: 'page', 
			url: '/page' ,
			controller: 'PageController',
                        controllerAs: '$ctrl',
			templateUrl: require('page.html')
		},
	}

})( angular );
```
page.controller.js
```
'use strict';
import angular from 'angular';

(function( angular ) {

	angular
		.module( 'page' )
		.controller('PageController', PageController);

	PageController.$inject = [
		'injections'
	];

	function PageController(
		injections
	){
		var $ctrl = this;
		$ctrl.$onInit = activate;


		function activate() {
		}
	}

})( angular );
```

And then it only matches all .module files and not the controllers or routes or other files

If i replace the preg match with:
`/(?:_?angular[0-9]?\s*(?:\.\s*default)?)?[.\s]+module\((["']?[\w.\-\/\\]+['"]?\s*(,\s*\[(?:[\w.,\s()\[\]'"@\/\\]*)\])?\s*)\)/g`

(added a optional capture group around the ,whitespace [ injections ] code)
it does match the files. But it's going into sourcemap errors:

> ERROR in ./scripts/pages/page.controller.js
> Module build failed: TypeError: Cannot read property 'substr' of undefined
>     at Function.<anonymous> (node_modules\source-map\lib\source-node.js:101:31)
>     at Array.forEach (<anonymous>)
>     at BasicSourceMapConsumer.SourceMapConsumer_eachMapping [as eachMapping] (node_modules\source-map\lib\source-map-consumer.js:155:14)
>     at Function.SourceNode_fromStringWithSourceMap [as fromStringWithSourceMap] (node_modules\source-map\lib\source-node.js:86:24)
>     at Object.transform (node_modules\angular-hot-loader\lib\loader.js:62:16)
>  @ ./pages/page/page.module.js
>  @ ./pages/common.module.js
>  @ ./scripts/app.module.js
>  @ ./scripts/angularjs-bootstrap.js
>  @ multi ../node_modules/webpack-dev-server/client?https://domain.ext:8080 webpack/hot/dev-server ./scripts/angularjs-bootstrap.js
> 

I'm still trying to figure it all out and fix it/add a pull request, but any help would be greatly appreciated

**Comment by aiwha-dev** [comment]
Ok it's only 36 files. Debugging one specifically to see if there is a reason for this error.

**Comment by aiwha-dev** [comment]
Ok it's when the code says

```
angular
	.module

```
instead of

`angular.module`

the compiled result is the same though

**Comment by aiwha-dev** [comment]
Created a pull request with my findings
https://github.com/vitaliy-bobrov/angular-hot-loader/pull/29

though i'm giving up on it. 
I excluded node_modules and then ran into errors of certain providers not being found
I included node_modules and then ran into errors within certain vendors

So i'd suggest to eather propperly test my update or ignore it. Since i can't get it to work completely.
